### ISSUE TITLE
Don't trust the front

### ISSUE THREAD

**Issue by Dyshay** [Rs-appez/dofuspoly_frontend#6]
https://github.com/Rs-appez/dofuspoly_frontend/blob/3ffe7660c2b8bddc6a9543c3423aefe744bff448/src/app/board/board.component.ts#L38

Call url from your back-end for determine random number

**Comment by Rs-appez** [comment]
yep, i keep the dice roll in front to simplify the development, it's planned to relocate it in back

**Comment by Dyshay** [comment]
You can create service and mock them
